# Generated by Django 5.1.4 on 2025-01-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=9)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
